// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sessions.proto

package session

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Version       uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_sessions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AddRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AddRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_sessions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{1}
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_sessions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteSessionRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *DeleteSessionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_sessions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{3}
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_sessions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UpdateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UpdateRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequestResponse) Reset() {
	*x = UpdateRequestResponse{}
	mi := &file_sessions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequestResponse) ProtoMessage() {}

func (x *UpdateRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequestResponse.ProtoReflect.Descriptor instead.
func (*UpdateRequestResponse) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{5}
}

type CheckVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Version       uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckVersionRequest) Reset() {
	*x = CheckVersionRequest{}
	mi := &file_sessions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckVersionRequest) ProtoMessage() {}

func (x *CheckVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckVersionRequest.ProtoReflect.Descriptor instead.
func (*CheckVersionRequest) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{6}
}

func (x *CheckVersionRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CheckVersionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CheckVersionRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type CheckVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasSession    bool                   `protobuf:"varint,1,opt,name=hasSession,proto3" json:"hasSession,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckVersionResponse) Reset() {
	*x = CheckVersionResponse{}
	mi := &file_sessions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckVersionResponse) ProtoMessage() {}

func (x *CheckVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckVersionResponse.ProtoReflect.Descriptor instead.
func (*CheckVersionResponse) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{7}
}

func (x *CheckVersionResponse) GetHasSession() bool {
	if x != nil {
		return x.HasSession
	}
	return false
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_sessions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{8}
}

func (x *GetVersionRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetVersionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_sessions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{9}
}

func (x *GetVersionResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type HasSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasSessionRequest) Reset() {
	*x = HasSessionRequest{}
	mi := &file_sessions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasSessionRequest) ProtoMessage() {}

func (x *HasSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasSessionRequest.ProtoReflect.Descriptor instead.
func (*HasSessionRequest) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{10}
}

func (x *HasSessionRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *HasSessionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HasSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasSessionResponse) Reset() {
	*x = HasSessionResponse{}
	mi := &file_sessions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasSessionResponse) ProtoMessage() {}

func (x *HasSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasSessionResponse.ProtoReflect.Descriptor instead.
func (*HasSessionResponse) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{11}
}

type CheckAllUserSessionTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAllUserSessionTokensRequest) Reset() {
	*x = CheckAllUserSessionTokensRequest{}
	mi := &file_sessions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAllUserSessionTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAllUserSessionTokensRequest) ProtoMessage() {}

func (x *CheckAllUserSessionTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAllUserSessionTokensRequest.ProtoReflect.Descriptor instead.
func (*CheckAllUserSessionTokensRequest) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{12}
}

func (x *CheckAllUserSessionTokensRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type CheckAllUserSessionTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAllUserSessionTokensResponse) Reset() {
	*x = CheckAllUserSessionTokensResponse{}
	mi := &file_sessions_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAllUserSessionTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAllUserSessionTokensResponse) ProtoMessage() {}

func (x *CheckAllUserSessionTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAllUserSessionTokensResponse.ProtoReflect.Descriptor instead.
func (*CheckAllUserSessionTokensResponse) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{13}
}

var File_sessions_proto protoreflect.FileDescriptor

const file_sessions_proto_rawDesc = "" +
	"\n" +
	"\x0esessions.proto\x12\asession\"R\n" +
	"\n" +
	"AddRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\"\r\n" +
	"\vAddResponse\"B\n" +
	"\x14DeleteSessionRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x17\n" +
	"\x15DeleteSessionResponse\";\n" +
	"\rUpdateRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x17\n" +
	"\x15UpdateRequestResponse\"[\n" +
	"\x13CheckVersionRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\"6\n" +
	"\x14CheckVersionResponse\x12\x1e\n" +
	"\n" +
	"hasSession\x18\x01 \x01(\bR\n" +
	"hasSession\"?\n" +
	"\x11GetVersionRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\".\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\"?\n" +
	"\x11HasSessionRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x14\n" +
	"\x12HasSessionResponse\"8\n" +
	" CheckAllUserSessionTokensRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\"#\n" +
	"!CheckAllUserSessionTokensResponse2\xab\x04\n" +
	"\bSessions\x122\n" +
	"\x03Add\x12\x13.session.AddRequest\x1a\x14.session.AddResponse\"\x00\x12P\n" +
	"\rDeleteSession\x12\x1d.session.DeleteSessionRequest\x1a\x1e.session.DeleteSessionResponse\"\x00\x12B\n" +
	"\x06Update\x12\x16.session.UpdateRequest\x1a\x1e.session.UpdateRequestResponse\"\x00\x12M\n" +
	"\fCheckVersion\x12\x1c.session.CheckVersionRequest\x1a\x1d.session.CheckVersionResponse\"\x00\x12G\n" +
	"\n" +
	"GetVersion\x12\x1a.session.GetVersionRequest\x1a\x1b.session.GetVersionResponse\"\x00\x12G\n" +
	"\n" +
	"HasSession\x12\x1a.session.HasSessionRequest\x1a\x1b.session.HasSessionResponse\"\x00\x12t\n" +
	"\x19CheckAllUserSessionTokens\x12).session.CheckAllUserSessionTokensRequest\x1a*.session.CheckAllUserSessionTokensResponse\"\x00B\vZ\t./sessionb\x06proto3"

var (
	file_sessions_proto_rawDescOnce sync.Once
	file_sessions_proto_rawDescData []byte
)

func file_sessions_proto_rawDescGZIP() []byte {
	file_sessions_proto_rawDescOnce.Do(func() {
		file_sessions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sessions_proto_rawDesc), len(file_sessions_proto_rawDesc)))
	})
	return file_sessions_proto_rawDescData
}

var file_sessions_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_sessions_proto_goTypes = []any{
	(*AddRequest)(nil),                        // 0: session.AddRequest
	(*AddResponse)(nil),                       // 1: session.AddResponse
	(*DeleteSessionRequest)(nil),              // 2: session.DeleteSessionRequest
	(*DeleteSessionResponse)(nil),             // 3: session.DeleteSessionResponse
	(*UpdateRequest)(nil),                     // 4: session.UpdateRequest
	(*UpdateRequestResponse)(nil),             // 5: session.UpdateRequestResponse
	(*CheckVersionRequest)(nil),               // 6: session.CheckVersionRequest
	(*CheckVersionResponse)(nil),              // 7: session.CheckVersionResponse
	(*GetVersionRequest)(nil),                 // 8: session.GetVersionRequest
	(*GetVersionResponse)(nil),                // 9: session.GetVersionResponse
	(*HasSessionRequest)(nil),                 // 10: session.HasSessionRequest
	(*HasSessionResponse)(nil),                // 11: session.HasSessionResponse
	(*CheckAllUserSessionTokensRequest)(nil),  // 12: session.CheckAllUserSessionTokensRequest
	(*CheckAllUserSessionTokensResponse)(nil), // 13: session.CheckAllUserSessionTokensResponse
}
var file_sessions_proto_depIdxs = []int32{
	0,  // 0: session.Sessions.Add:input_type -> session.AddRequest
	2,  // 1: session.Sessions.DeleteSession:input_type -> session.DeleteSessionRequest
	4,  // 2: session.Sessions.Update:input_type -> session.UpdateRequest
	6,  // 3: session.Sessions.CheckVersion:input_type -> session.CheckVersionRequest
	8,  // 4: session.Sessions.GetVersion:input_type -> session.GetVersionRequest
	10, // 5: session.Sessions.HasSession:input_type -> session.HasSessionRequest
	12, // 6: session.Sessions.CheckAllUserSessionTokens:input_type -> session.CheckAllUserSessionTokensRequest
	1,  // 7: session.Sessions.Add:output_type -> session.AddResponse
	3,  // 8: session.Sessions.DeleteSession:output_type -> session.DeleteSessionResponse
	5,  // 9: session.Sessions.Update:output_type -> session.UpdateRequestResponse
	7,  // 10: session.Sessions.CheckVersion:output_type -> session.CheckVersionResponse
	9,  // 11: session.Sessions.GetVersion:output_type -> session.GetVersionResponse
	11, // 12: session.Sessions.HasSession:output_type -> session.HasSessionResponse
	13, // 13: session.Sessions.CheckAllUserSessionTokens:output_type -> session.CheckAllUserSessionTokensResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_sessions_proto_init() }
func file_sessions_proto_init() {
	if File_sessions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sessions_proto_rawDesc), len(file_sessions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sessions_proto_goTypes,
		DependencyIndexes: file_sessions_proto_depIdxs,
		MessageInfos:      file_sessions_proto_msgTypes,
	}.Build()
	File_sessions_proto = out.File
	file_sessions_proto_goTypes = nil
	file_sessions_proto_depIdxs = nil
}
