// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: users.proto

package session

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserSignUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSignUp) Reset() {
	*x = UserSignUp{}
	mi := &file_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSignUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignUp) ProtoMessage() {}

func (x *UserSignUp) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignUp.ProtoReflect.Descriptor instead.
func (*UserSignUp) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{0}
}

func (x *UserSignUp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSignUp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserSignUp) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uuid            string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email           string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username        string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password        string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Version         uint32                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	IsAdmin         bool                   `protobuf:"varint,6,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	Avatar          string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Birthday        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday,omitempty"`
	RegisteredAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=registeredAt,proto3" json:"registeredAt,omitempty"`
	HasSubscription bool                   `protobuf:"varint,10,opt,name=HasSubscription,proto3" json:"HasSubscription,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *User) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *User) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *User) GetHasSubscription() bool {
	if x != nil {
		return x.HasSubscription
	}
	return false
}

type UserPreview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPreview) Reset() {
	*x = UserPreview{}
	mi := &file_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreview) ProtoMessage() {}

func (x *UserPreview) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreview.ProtoReflect.Descriptor instead.
func (*UserPreview) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{2}
}

func (x *UserPreview) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UserPreview) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserPreview) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserSignUp            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserRequest) GetUser() *UserSignUp {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{4}
}

type RemoveUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRequest) Reset() {
	*x = RemoveUserRequest{}
	mi := &file_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRequest) ProtoMessage() {}

func (x *RemoveUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type RemoveUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserResponse) Reset() {
	*x = RemoveUserResponse{}
	mi := &file_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserResponse) ProtoMessage() {}

func (x *RemoveUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{6}
}

type HasUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasUserRequest) Reset() {
	*x = HasUserRequest{}
	mi := &file_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasUserRequest) ProtoMessage() {}

func (x *HasUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasUserRequest.ProtoReflect.Descriptor instead.
func (*HasUserRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{7}
}

func (x *HasUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *HasUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type HasUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Has           bool                   `protobuf:"varint,1,opt,name=has,proto3" json:"has,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasUserResponse) Reset() {
	*x = HasUserResponse{}
	mi := &file_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasUserResponse) ProtoMessage() {}

func (x *HasUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasUserResponse.ProtoReflect.Descriptor instead.
func (*HasUserResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{8}
}

func (x *HasUserResponse) GetHas() bool {
	if x != nil {
		return x.Has
	}
	return false
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_users_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ChangeUserPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserPasswordRequest) Reset() {
	*x = ChangeUserPasswordRequest{}
	mi := &file_users_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserPasswordRequest) ProtoMessage() {}

func (x *ChangeUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangeUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeUserPasswordRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ChangeUserPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangeUserPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserPasswordResponse) Reset() {
	*x = ChangeUserPasswordResponse{}
	mi := &file_users_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserPasswordResponse) ProtoMessage() {}

func (x *ChangeUserPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserPasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangeUserPasswordResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeUserPasswordResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ChangeUserNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	NewUsername   string                 `protobuf:"bytes,2,opt,name=newUsername,proto3" json:"newUsername,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserNameRequest) Reset() {
	*x = ChangeUserNameRequest{}
	mi := &file_users_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserNameRequest) ProtoMessage() {}

func (x *ChangeUserNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserNameRequest.ProtoReflect.Descriptor instead.
func (*ChangeUserNameRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{13}
}

func (x *ChangeUserNameRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ChangeUserNameRequest) GetNewUsername() string {
	if x != nil {
		return x.NewUsername
	}
	return ""
}

type ChangeUserNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserNameResponse) Reset() {
	*x = ChangeUserNameResponse{}
	mi := &file_users_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserNameResponse) ProtoMessage() {}

func (x *ChangeUserNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserNameResponse.ProtoReflect.Descriptor instead.
func (*ChangeUserNameResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{14}
}

func (x *ChangeUserNameResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserDataByUuidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDataByUuidRequest) Reset() {
	*x = GetUserDataByUuidRequest{}
	mi := &file_users_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataByUuidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataByUuidRequest) ProtoMessage() {}

func (x *GetUserDataByUuidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataByUuidRequest.ProtoReflect.Descriptor instead.
func (*GetUserDataByUuidRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserDataByUuidRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetUserDataByUuidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDataByUuidResponse) Reset() {
	*x = GetUserDataByUuidResponse{}
	mi := &file_users_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataByUuidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataByUuidResponse) ProtoMessage() {}

func (x *GetUserDataByUuidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataByUuidResponse.ProtoReflect.Descriptor instead.
func (*GetUserDataByUuidResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserDataByUuidResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserPreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPreviewRequest) Reset() {
	*x = GetUserPreviewRequest{}
	mi := &file_users_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPreviewRequest) ProtoMessage() {}

func (x *GetUserPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPreviewRequest.ProtoReflect.Descriptor instead.
func (*GetUserPreviewRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserPreviewRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetUserPreviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserPreview           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPreviewResponse) Reset() {
	*x = GetUserPreviewResponse{}
	mi := &file_users_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPreviewResponse) ProtoMessage() {}

func (x *GetUserPreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPreviewResponse.ProtoReflect.Descriptor instead.
func (*GetUserPreviewResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserPreviewResponse) GetUser() *UserPreview {
	if x != nil {
		return x.User
	}
	return nil
}

type ChangeUserPasswordByUuidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserPasswordByUuidRequest) Reset() {
	*x = ChangeUserPasswordByUuidRequest{}
	mi := &file_users_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserPasswordByUuidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserPasswordByUuidRequest) ProtoMessage() {}

func (x *ChangeUserPasswordByUuidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserPasswordByUuidRequest.ProtoReflect.Descriptor instead.
func (*ChangeUserPasswordByUuidRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{19}
}

func (x *ChangeUserPasswordByUuidRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ChangeUserPasswordByUuidRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangeUserPasswordByUuidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserPasswordByUuidResponse) Reset() {
	*x = ChangeUserPasswordByUuidResponse{}
	mi := &file_users_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserPasswordByUuidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserPasswordByUuidResponse) ProtoMessage() {}

func (x *ChangeUserPasswordByUuidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserPasswordByUuidResponse.ProtoReflect.Descriptor instead.
func (*ChangeUserPasswordByUuidResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{20}
}

func (x *ChangeUserPasswordByUuidResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ChangeUserNameByUuidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	NewUsername   string                 `protobuf:"bytes,2,opt,name=newUsername,proto3" json:"newUsername,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserNameByUuidRequest) Reset() {
	*x = ChangeUserNameByUuidRequest{}
	mi := &file_users_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserNameByUuidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserNameByUuidRequest) ProtoMessage() {}

func (x *ChangeUserNameByUuidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserNameByUuidRequest.ProtoReflect.Descriptor instead.
func (*ChangeUserNameByUuidRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{21}
}

func (x *ChangeUserNameByUuidRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ChangeUserNameByUuidRequest) GetNewUsername() string {
	if x != nil {
		return x.NewUsername
	}
	return ""
}

type ChangeUserNameByUuidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserNameByUuidResponse) Reset() {
	*x = ChangeUserNameByUuidResponse{}
	mi := &file_users_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserNameByUuidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserNameByUuidResponse) ProtoMessage() {}

func (x *ChangeUserNameByUuidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserNameByUuidResponse.ProtoReflect.Descriptor instead.
func (*ChangeUserNameByUuidResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{22}
}

func (x *ChangeUserNameByUuidResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ChangeUserAvatarByUuidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	NewAvatar     string                 `protobuf:"bytes,2,opt,name=newAvatar,proto3" json:"newAvatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserAvatarByUuidRequest) Reset() {
	*x = ChangeUserAvatarByUuidRequest{}
	mi := &file_users_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserAvatarByUuidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserAvatarByUuidRequest) ProtoMessage() {}

func (x *ChangeUserAvatarByUuidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserAvatarByUuidRequest.ProtoReflect.Descriptor instead.
func (*ChangeUserAvatarByUuidRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{23}
}

func (x *ChangeUserAvatarByUuidRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ChangeUserAvatarByUuidRequest) GetNewAvatar() string {
	if x != nil {
		return x.NewAvatar
	}
	return ""
}

type ChangeUserAvatarByUuidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserAvatarByUuidResponse) Reset() {
	*x = ChangeUserAvatarByUuidResponse{}
	mi := &file_users_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserAvatarByUuidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserAvatarByUuidResponse) ProtoMessage() {}

func (x *ChangeUserAvatarByUuidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserAvatarByUuidResponse.ProtoReflect.Descriptor instead.
func (*ChangeUserAvatarByUuidResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{24}
}

func (x *ChangeUserAvatarByUuidResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type HasSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasSubscriptionRequest) Reset() {
	*x = HasSubscriptionRequest{}
	mi := &file_users_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasSubscriptionRequest) ProtoMessage() {}

func (x *HasSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*HasSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{25}
}

func (x *HasSubscriptionRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type HasSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasSubscriptionResponse) Reset() {
	*x = HasSubscriptionResponse{}
	mi := &file_users_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasSubscriptionResponse) ProtoMessage() {}

func (x *HasSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*HasSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{26}
}

func (x *HasSubscriptionResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Duration      uint32                 `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_users_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{27}
}

func (x *Subscription) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Subscription) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Subscription) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Subscription) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Subscription) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type GetSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsRequest) Reset() {
	*x = GetSubscriptionsRequest{}
	mi := &file_users_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsRequest) ProtoMessage() {}

func (x *GetSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{28}
}

type GetSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsResponse) Reset() {
	*x = GetSubscriptionsResponse{}
	mi := &file_users_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsResponse) ProtoMessage() {}

func (x *GetSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{29}
}

func (x *GetSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type PaySubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SubId         string                 `protobuf:"bytes,2,opt,name=subId,proto3" json:"subId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaySubscriptionRequest) Reset() {
	*x = PaySubscriptionRequest{}
	mi := &file_users_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaySubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaySubscriptionRequest) ProtoMessage() {}

func (x *PaySubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaySubscriptionRequest.ProtoReflect.Descriptor instead.
func (*PaySubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{30}
}

func (x *PaySubscriptionRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PaySubscriptionRequest) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

type PaySubscriptionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentResponse string                 `protobuf:"bytes,1,opt,name=paymentResponse,proto3" json:"paymentResponse,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaySubscriptionResponse) Reset() {
	*x = PaySubscriptionResponse{}
	mi := &file_users_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaySubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaySubscriptionResponse) ProtoMessage() {}

func (x *PaySubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaySubscriptionResponse.ProtoReflect.Descriptor instead.
func (*PaySubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{31}
}

func (x *PaySubscriptionResponse) GetPaymentResponse() string {
	if x != nil {
		return x.PaymentResponse
	}
	return ""
}

var File_users_proto protoreflect.FileDescriptor

const file_users_proto_rawDesc = "" +
	"\n" +
	"\vusers.proto\x12\asession\x1a\x1fgoogle/protobuf/timestamp.proto\"Z\n" +
	"\n" +
	"UserSignUp\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\xd6\x02\n" +
	"\x04User\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x18\n" +
	"\aversion\x18\x05 \x01(\rR\aversion\x12\x18\n" +
	"\aisAdmin\x18\x06 \x01(\bR\aisAdmin\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x126\n" +
	"\bbirthday\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bbirthday\x12>\n" +
	"\fregisteredAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12(\n" +
	"\x0fHasSubscription\x18\n" +
	" \x01(\bR\x0fHasSubscription\"U\n" +
	"\vUserPreview\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"<\n" +
	"\x11CreateUserRequest\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.session.UserSignUpR\x04user\"\x14\n" +
	"\x12CreateUserResponse\")\n" +
	"\x11RemoveUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\"\x14\n" +
	"\x12RemoveUserResponse\"B\n" +
	"\x0eHasUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"#\n" +
	"\x0fHasUserResponse\x12\x10\n" +
	"\x03has\x18\x01 \x01(\bR\x03has\"&\n" +
	"\x0eGetUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\"4\n" +
	"\x0fGetUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.session.UserR\x04user\"S\n" +
	"\x19ChangeUserPasswordRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12 \n" +
	"\vnewPassword\x18\x02 \x01(\tR\vnewPassword\"?\n" +
	"\x1aChangeUserPasswordResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.session.UserR\x04user\"O\n" +
	"\x15ChangeUserNameRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12 \n" +
	"\vnewUsername\x18\x02 \x01(\tR\vnewUsername\";\n" +
	"\x16ChangeUserNameResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.session.UserR\x04user\".\n" +
	"\x18GetUserDataByUuidRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\">\n" +
	"\x19GetUserDataByUuidResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.session.UserR\x04user\"+\n" +
	"\x15GetUserPreviewRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"B\n" +
	"\x16GetUserPreviewResponse\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.session.UserPreviewR\x04user\"W\n" +
	"\x1fChangeUserPasswordByUuidRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12 \n" +
	"\vnewPassword\x18\x02 \x01(\tR\vnewPassword\"E\n" +
	" ChangeUserPasswordByUuidResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.session.UserR\x04user\"S\n" +
	"\x1bChangeUserNameByUuidRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12 \n" +
	"\vnewUsername\x18\x02 \x01(\tR\vnewUsername\"A\n" +
	"\x1cChangeUserNameByUuidResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.session.UserR\x04user\"Q\n" +
	"\x1dChangeUserAvatarByUuidRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1c\n" +
	"\tnewAvatar\x18\x02 \x01(\tR\tnewAvatar\"C\n" +
	"\x1eChangeUserAvatarByUuidResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.session.UserR\x04user\",\n" +
	"\x16HasSubscriptionRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"1\n" +
	"\x17HasSubscriptionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"\x8c\x01\n" +
	"\fSubscription\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\rR\bduration\"\x19\n" +
	"\x17GetSubscriptionsRequest\"W\n" +
	"\x18GetSubscriptionsResponse\x12;\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x15.session.SubscriptionR\rsubscriptions\"B\n" +
	"\x16PaySubscriptionRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05subId\x18\x02 \x01(\tR\x05subId\"C\n" +
	"\x17PaySubscriptionResponse\x12(\n" +
	"\x0fpaymentResponse\x18\x01 \x01(\tR\x0fpaymentResponse2\xd4\t\n" +
	"\x05Users\x12G\n" +
	"\n" +
	"CreateUser\x12\x1a.session.CreateUserRequest\x1a\x1b.session.CreateUserResponse\"\x00\x12G\n" +
	"\n" +
	"RemoveUser\x12\x1a.session.RemoveUserRequest\x1a\x1b.session.RemoveUserResponse\"\x00\x12>\n" +
	"\aHasUser\x12\x17.session.HasUserRequest\x1a\x18.session.HasUserResponse\"\x00\x12>\n" +
	"\aGetUser\x12\x17.session.GetUserRequest\x1a\x18.session.GetUserResponse\"\x00\x12_\n" +
	"\x12ChangeUserPassword\x12\".session.ChangeUserPasswordRequest\x1a#.session.ChangeUserPasswordResponse\"\x00\x12S\n" +
	"\x0eChangeUserName\x12\x1e.session.ChangeUserNameRequest\x1a\x1f.session.ChangeUserNameResponse\"\x00\x12\\\n" +
	"\x11GetUserDataByUuid\x12!.session.GetUserDataByUuidRequest\x1a\".session.GetUserDataByUuidResponse\"\x00\x12S\n" +
	"\x0eGetUserPreview\x12\x1e.session.GetUserPreviewRequest\x1a\x1f.session.GetUserPreviewResponse\"\x00\x12q\n" +
	"\x18ChangeUserPasswordByUuid\x12(.session.ChangeUserPasswordByUuidRequest\x1a).session.ChangeUserPasswordByUuidResponse\"\x00\x12e\n" +
	"\x14ChangeUserNameByUuid\x12$.session.ChangeUserNameByUuidRequest\x1a%.session.ChangeUserNameByUuidResponse\"\x00\x12k\n" +
	"\x16ChangeUserAvatarByUuid\x12&.session.ChangeUserAvatarByUuidRequest\x1a'.session.ChangeUserAvatarByUuidResponse\"\x00\x12V\n" +
	"\x0fHasSubscription\x12\x1f.session.HasSubscriptionRequest\x1a .session.HasSubscriptionResponse\"\x00\x12Y\n" +
	"\x10GetSubscriptions\x12 .session.GetSubscriptionsRequest\x1a!.session.GetSubscriptionsResponse\"\x00\x12V\n" +
	"\x0fPaySubscription\x12\x1f.session.PaySubscriptionRequest\x1a .session.PaySubscriptionResponse\"\x00B\vZ\t./sessionb\x06proto3"

var (
	file_users_proto_rawDescOnce sync.Once
	file_users_proto_rawDescData []byte
)

func file_users_proto_rawDescGZIP() []byte {
	file_users_proto_rawDescOnce.Do(func() {
		file_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)))
	})
	return file_users_proto_rawDescData
}

var file_users_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_users_proto_goTypes = []any{
	(*UserSignUp)(nil),                       // 0: session.UserSignUp
	(*User)(nil),                             // 1: session.User
	(*UserPreview)(nil),                      // 2: session.UserPreview
	(*CreateUserRequest)(nil),                // 3: session.CreateUserRequest
	(*CreateUserResponse)(nil),               // 4: session.CreateUserResponse
	(*RemoveUserRequest)(nil),                // 5: session.RemoveUserRequest
	(*RemoveUserResponse)(nil),               // 6: session.RemoveUserResponse
	(*HasUserRequest)(nil),                   // 7: session.HasUserRequest
	(*HasUserResponse)(nil),                  // 8: session.HasUserResponse
	(*GetUserRequest)(nil),                   // 9: session.GetUserRequest
	(*GetUserResponse)(nil),                  // 10: session.GetUserResponse
	(*ChangeUserPasswordRequest)(nil),        // 11: session.ChangeUserPasswordRequest
	(*ChangeUserPasswordResponse)(nil),       // 12: session.ChangeUserPasswordResponse
	(*ChangeUserNameRequest)(nil),            // 13: session.ChangeUserNameRequest
	(*ChangeUserNameResponse)(nil),           // 14: session.ChangeUserNameResponse
	(*GetUserDataByUuidRequest)(nil),         // 15: session.GetUserDataByUuidRequest
	(*GetUserDataByUuidResponse)(nil),        // 16: session.GetUserDataByUuidResponse
	(*GetUserPreviewRequest)(nil),            // 17: session.GetUserPreviewRequest
	(*GetUserPreviewResponse)(nil),           // 18: session.GetUserPreviewResponse
	(*ChangeUserPasswordByUuidRequest)(nil),  // 19: session.ChangeUserPasswordByUuidRequest
	(*ChangeUserPasswordByUuidResponse)(nil), // 20: session.ChangeUserPasswordByUuidResponse
	(*ChangeUserNameByUuidRequest)(nil),      // 21: session.ChangeUserNameByUuidRequest
	(*ChangeUserNameByUuidResponse)(nil),     // 22: session.ChangeUserNameByUuidResponse
	(*ChangeUserAvatarByUuidRequest)(nil),    // 23: session.ChangeUserAvatarByUuidRequest
	(*ChangeUserAvatarByUuidResponse)(nil),   // 24: session.ChangeUserAvatarByUuidResponse
	(*HasSubscriptionRequest)(nil),           // 25: session.HasSubscriptionRequest
	(*HasSubscriptionResponse)(nil),          // 26: session.HasSubscriptionResponse
	(*Subscription)(nil),                     // 27: session.Subscription
	(*GetSubscriptionsRequest)(nil),          // 28: session.GetSubscriptionsRequest
	(*GetSubscriptionsResponse)(nil),         // 29: session.GetSubscriptionsResponse
	(*PaySubscriptionRequest)(nil),           // 30: session.PaySubscriptionRequest
	(*PaySubscriptionResponse)(nil),          // 31: session.PaySubscriptionResponse
	(*timestamppb.Timestamp)(nil),            // 32: google.protobuf.Timestamp
}
var file_users_proto_depIdxs = []int32{
	32, // 0: session.User.birthday:type_name -> google.protobuf.Timestamp
	32, // 1: session.User.registeredAt:type_name -> google.protobuf.Timestamp
	0,  // 2: session.CreateUserRequest.user:type_name -> session.UserSignUp
	1,  // 3: session.GetUserResponse.user:type_name -> session.User
	1,  // 4: session.ChangeUserPasswordResponse.user:type_name -> session.User
	1,  // 5: session.ChangeUserNameResponse.user:type_name -> session.User
	1,  // 6: session.GetUserDataByUuidResponse.user:type_name -> session.User
	2,  // 7: session.GetUserPreviewResponse.user:type_name -> session.UserPreview
	1,  // 8: session.ChangeUserPasswordByUuidResponse.user:type_name -> session.User
	1,  // 9: session.ChangeUserNameByUuidResponse.user:type_name -> session.User
	1,  // 10: session.ChangeUserAvatarByUuidResponse.user:type_name -> session.User
	27, // 11: session.GetSubscriptionsResponse.subscriptions:type_name -> session.Subscription
	3,  // 12: session.Users.CreateUser:input_type -> session.CreateUserRequest
	5,  // 13: session.Users.RemoveUser:input_type -> session.RemoveUserRequest
	7,  // 14: session.Users.HasUser:input_type -> session.HasUserRequest
	9,  // 15: session.Users.GetUser:input_type -> session.GetUserRequest
	11, // 16: session.Users.ChangeUserPassword:input_type -> session.ChangeUserPasswordRequest
	13, // 17: session.Users.ChangeUserName:input_type -> session.ChangeUserNameRequest
	15, // 18: session.Users.GetUserDataByUuid:input_type -> session.GetUserDataByUuidRequest
	17, // 19: session.Users.GetUserPreview:input_type -> session.GetUserPreviewRequest
	19, // 20: session.Users.ChangeUserPasswordByUuid:input_type -> session.ChangeUserPasswordByUuidRequest
	21, // 21: session.Users.ChangeUserNameByUuid:input_type -> session.ChangeUserNameByUuidRequest
	23, // 22: session.Users.ChangeUserAvatarByUuid:input_type -> session.ChangeUserAvatarByUuidRequest
	25, // 23: session.Users.HasSubscription:input_type -> session.HasSubscriptionRequest
	28, // 24: session.Users.GetSubscriptions:input_type -> session.GetSubscriptionsRequest
	30, // 25: session.Users.PaySubscription:input_type -> session.PaySubscriptionRequest
	4,  // 26: session.Users.CreateUser:output_type -> session.CreateUserResponse
	6,  // 27: session.Users.RemoveUser:output_type -> session.RemoveUserResponse
	8,  // 28: session.Users.HasUser:output_type -> session.HasUserResponse
	10, // 29: session.Users.GetUser:output_type -> session.GetUserResponse
	12, // 30: session.Users.ChangeUserPassword:output_type -> session.ChangeUserPasswordResponse
	14, // 31: session.Users.ChangeUserName:output_type -> session.ChangeUserNameResponse
	16, // 32: session.Users.GetUserDataByUuid:output_type -> session.GetUserDataByUuidResponse
	18, // 33: session.Users.GetUserPreview:output_type -> session.GetUserPreviewResponse
	20, // 34: session.Users.ChangeUserPasswordByUuid:output_type -> session.ChangeUserPasswordByUuidResponse
	22, // 35: session.Users.ChangeUserNameByUuid:output_type -> session.ChangeUserNameByUuidResponse
	24, // 36: session.Users.ChangeUserAvatarByUuid:output_type -> session.ChangeUserAvatarByUuidResponse
	26, // 37: session.Users.HasSubscription:output_type -> session.HasSubscriptionResponse
	29, // 38: session.Users.GetSubscriptions:output_type -> session.GetSubscriptionsResponse
	31, // 39: session.Users.PaySubscription:output_type -> session.PaySubscriptionResponse
	26, // [26:40] is the sub-list for method output_type
	12, // [12:26] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_users_proto_init() }
func file_users_proto_init() {
	if File_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_proto_goTypes,
		DependencyIndexes: file_users_proto_depIdxs,
		MessageInfos:      file_users_proto_msgTypes,
	}.Build()
	File_users_proto = out.File
	file_users_proto_goTypes = nil
	file_users_proto_depIdxs = nil
}
